mode: inference

data:
  inference_input:
    dir: /mnt/eternus/users/Yu/project/data_compression/experiment/paper_exp/3d/compression/bmshj2018-factorized_ms-ssim_8_v2
    #users/Jianxu/projects/im2im_experiments_v1/data/labelfree3D/FBL/holdout   #ADD-YOURS
    data_type: .tiff  # this will search only files with name *_IM.tiff
    reader_params:
      dimension_order_out: "ZYX"
      C: 0
      T: 0
  inference_output:
    path: /mnt/eternus/users/Yu/project/data_compression/experiment/paper_exp/3d/labelfree/prediction/compressed
  preprocess:      
    - module_name: mmv_im2im.preprocessing.transforms
      func_name: norm_around_center
      params:
        min_z: 32      
    # - module_name: monai.transforms
    #   func_name: ScaleIntensityRangePercentiles
    #   params:
    #     lower: 0.5
    #     upper: 99.5
    #     b_min: -1
    #     b_max: 1
    # - module_name: monai.transforms
    #   func_name: NormalizeIntensity  

model:
  framework: FCN
  net:
    module_name: mmv_im2im.models.nets.fnet_nn_3d
    func_name: Net
    params:
      depth: 4
      mult_chan: 32
      in_channels: 1
      out_channels: 1    
  checkpoint: /mnt/eternus/users/Yu/project/data_compression/experiment/paper_exp/3d/labelfree/labelfree_3d.ckpt  #ADD-YOURS
  model_extra:
    sliding_window_params:
      roi_size: [32, 128, 128]
      sw_batch_size: 4
      overlap: 0.2
      mode: "gaussian"